### ISSUE TITLE
Can not complete download header

### ISSUE THREAD

**Issue by duyld2108** [near/stakewars-iii#90] opened 2022-08-06 05:57 UTC
It's seem may be have error in commit **68bfa84ed1455f891032434d37ccad696e91e4f5**

Can not complete download header

Wrong chain_id (image bellow)

![image](https://user-images.githubusercontent.com/9260564/183236252-c73f5fd4-3fd9-4cf1-9450-014a48f935bb.png)

**Comment by DDeAlmeida** [comment] 2022-08-08 08:58
Please read the message, he said that you try to connect to someone how have misconfigure the node.
Please remove data folder and retry.

**Comment by ivanguardia** [comment] 2022-08-09 16:27
Indeed, It usually works deleting data and restart sync.
Download last config and genesis previously.

**Comment by stiavnik** [comment] 2022-08-09 19:04
For me this looks like someone ELSE is trying to run with mainnet genesis, how could this happen? Following all instructions EXCEPT downloading wrong genesis? (yes we don't need to do that, but could this be the cause?)

**Comment by DDeAlmeida** [comment] 2022-08-29 09:21
> For me this looks like someone ELSE is trying to run with mainnet genesis, how could this happen? Following all instructions EXCEPT downloading wrong genesis? (yes we don't need to do that, but could this be the cause?)

just someone who didn't follow guide or try something.
Closing the issue

**Closed by DDeAlmeida** 2022-08-29 09:21 UTC
